version: '3.3'

services:
  database:
    container_name: gs_produto_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=gs_produto
      - POSTGRES_USER=gs_produto
    ports:
      - 5434:5432
